/*-- VARIABLES ENVIRONMENT and DATABASE --*/
SET v_env_name='{replace_with_v_env_name}';
SET v_data_engineer_role=concat('data_engineer_role',$v_env_name);
SET v_db_name=concat('clean_db',$v_env_name);

/*-- SCHEMA CONTEXT --*/
USE ROLE identifier($v_data_engineer_role);
USE DATABASE identifier($v_db_name);
USE SCHEMA dnb;

CREATE TABLE IF NOT EXISTS DNB_UK_ORGANISATION (
  DUNS NUMBER NOT NULL,
  PRIMARY_INDUSTRY_CODE_USSICV4 NUMBER,
  PRIMARY_INDUSTRY_CODE_USSICV4DESCRIPTION VARCHAR(255),
  PRIMARY_NAME VARCHAR(255),
  START_DATE DATE,
  REGISTERED_NAME VARCHAR(255),
  INCORPORATED_DATE DATE,
  DEFAULT_CURRENCY VARCHAR(10),
  IS_STANDALONE BOOLEAN,
  IS_FORTUNE1000_LISTED BOOLEAN,
  LEGAL_FORM_DESCRIPTION VARCHAR(255),
  LEGAL_FORM_DNB_CODE NUMBER,
  LEGAL_FORM_START_DATE NUMBER,
  NUMBER_OF_EMPLOYEES_VALUE NUMBER,
  EMPLOYEE_FIGURES_DATE DATE,
  INFORMATION_SCOPE_DESCRIPTION VARCHAR(255),
  INFORMATION_SCOPE_DNB_CODE NUMBER,
  RELIABILITY_DESCRIPTION VARCHAR(255),
  RELIABILITY_DNB_CODE NUMBER,
  REGISTRATION_NUMBER NUMBER,
  REGISTRATION_TYPE_DESCRIPTION VARCHAR(255),
  REGISTRATION_TYPE_DNB_CODE NUMBER,
  IS_PREFERRED_REGISTRATION_NUMBER BOOLEAN,
  REGISTERED_ADDRESS_LANGUAGE  VARCHAR(255),
  REGISTERED_ADDRESS_COUNTRY  VARCHAR(255),
  REGISTERED_ADDRESS_ISOALPHA2CODE  VARCHAR(2),
  REGISTERED_ADDRESS_LOCALITY_NAME VARCHAR(255),
  REGISTERED_ADDRESS_MINOR_TOWN_NAME VARCHAR(255),
  REGISTERED_ADDRESS_REGION_NAME VARCHAR(255),
  REGISTERED_ADDRESS_COUNTY_NAME  VARCHAR(255),
  REGISTERED_ADDRESS_POSTAL_CODE VARCHAR(50),
  REGISTERED_ADDRESS_POSTAL_CODE_POSITION VARCHAR(255),
  REGISTERED_ADDRESS_STREET_NUMBER VARCHAR(255),
  REGISTERED_ADDRESS_STREET_NAME VARCHAR(255),
  ORGANIZATION_SIZE_CATEGORY_DESCRIPTION VARCHAR(255),
  ORGANIZATION_SIZE_CATEGORY_DNB_CODE NUMBER,
  PRIMARY_ADDRESS_LANGUAGE  VARCHAR(255),
  PRIMARY_ADDRESS_COUNTRY  VARCHAR(255),
  PRIMARY_ADDRESS_ISOALPHA2CODE  VARCHAR(2),
  PRIMARY_ADDRESS_CONTINENTAL_REGION  VARCHAR(255),
  PRIMARY_ADDRESS_LOCALITY_NAME VARCHAR(255),
  PRIMARY_ADDRESS_MINOR_TOWN_NAME VARCHAR(255),
  PRIMARY_ADDRESS_REGION_NAME VARCHAR(255),
  PRIMARY_ADDRESS_COUNTY_NAME  VARCHAR(255),
  PRIMARY_ADDRESS_POSTAL_CODE VARCHAR(50),
  PRIMARY_ADDRESS_POSTAL_CODE_POSITION VARCHAR(255),
  PRIMARY_ADDRESS_STREET_ADDRESS_LINE1 VARCHAR(255),
  PRIMARY_ADDRESS_STREET_ADDRESS_LINE2 VARCHAR(255),
  PRIMARY_ADDRESS_STREET_NUMBER VARCHAR(255),
  PRIMARY_ADDRESS_STREET_NAME VARCHAR(255),
  PRIMARY_ADDRESS_LATITUDE  NUMBER(38,10),
  PRIMARY_ADDRESS_LONGITUDE NUMBER(38,10),
  PRIMARY_ADDRESS_GEOGRAPHICAL_PRECISION_DESCRIPTION VARCHAR(255),
  DUNS_CONTROL_OPERATING_STATUS_DESCRIPTION VARCHAR(255),
  DUNS_CONTROL_OPERATING_STATUS_STARTDATE DATE,
  DUNS_CONTROL_OPERATING_SUB_STATUS_DESCRIPTION VARCHAR(255),
  DUNS_CONTROL_OPERATING_SUB_STATUS_STARTDATE DATE,
  DUNS_CONTROL_DETAILED_OPERATING_STATUS_DESCRIPTION VARCHAR(255),
  DUNS_CONTROL_IS_MARKETABLE BOOLEAN,
  DUNS_CONTROL_IS_MAIL_UNDELIVERABLE BOOLEAN,
  DUNS_CONTROL_IS_TELEPHONE_DISCONNECTED BOOLEAN,
  DUNS_CONTROL_IS_DELISTED BOOLEAN,
  PREFERRED_LANGUAGE_DESCRIPTION VARCHAR(255),
  BUSINESS_ENTITY_TYPE_DESCRIPTION VARCHAR(255),
  REGISTERED_DETAILS_LEGALFORM_DESCRIPTION VARCHAR(255),  
  CDW_LAST_MODIFIED_TIMESTAMP TIMESTAMP_NTZ(3) NOT NULL COMMENT 'Timestamp when the record was modified in the Corporate Data Warehouse',
  CDW_CDC_FLAG VARCHAR(1) NOT NULL COMMENT 'Change Data Capture flag that indicates whether the row is new (N), has changed (C), or it was deleted (D) compared to the active record in the Corporate Data Warehouse',
  CDW_START_DATE TIMESTAMP_NTZ(0) NOT NULL COMMENT 'Timestamp from when the record is active in the Corporate Data Warehouse',
  CDW_END_DATE TIMESTAMP_NTZ(0) NOT NULL COMMENT 'Timestamp from when the record is inactive in the Corporate Data Warehouse; the active record will have the value 9999-12-31 00:00:00'
);

/*-- REMOVE VARIABLES ENVIRONMENT and DATABASE --*/
unset v_env_name;
unset v_db_name;
unset v_data_engineer_role;